using System.Linq;
using UnityEngine;
namespace FpsStage2 {
// Two-bone reload IK. Segment lengths and the authored wrist pose are preserved.
[DefaultExecutionOrder(30)] public sealed class CPBotReload:MonoBehaviour {
 CPActor actor;Transform upper,fore,hand,weapon,prop;Renderer propRenderer;float started,duration;int serial;Material material;
 void Start(){actor=GetComponent<CPActor>();if(actor.characterClass!=ClassId.Scout&&actor.characterClass!=ClassId.Soldier){enabled=false;return;}var bones=GetComponentsInChildren<Transform>();upper=bones.FirstOrDefault(t=>t.name=="LeftArm");fore=bones.FirstOrDefault(t=>t.name=="LeftForeArm");hand=bones.FirstOrDefault(t=>t.name=="LeftHand");weapon=bones.FirstOrDefault(t=>t.name==actor.characterClass+"_Weapon");if(upper==null||fore==null||hand==null||weapon==null){enabled=false;return;}prop=new GameObject("Reload_Ammo_Prop").transform;prop.SetParent(transform,false);material=new Material(Shader.Find("Universal Render Pipeline/Lit"));material.color=actor.characterClass==ClassId.Scout?new Color(.62f,.18f,.075f):new Color(.7f,.57f,.16f);int count=actor.characterClass==ClassId.Scout?2:1;for(int i=0;i<count;i++){var p=GameObject.CreatePrimitive(PrimitiveType.Capsule);Destroy(p.GetComponent<Collider>());p.transform.SetParent(prop,false);p.transform.localRotation=Quaternion.Euler(90,0,0);p.transform.localPosition=new Vector3(i*.045f,0,0);p.transform.localScale=actor.characterClass==ClassId.Scout?new Vector3(.025f,.05f,.025f):new Vector3(.075f,.14f,.075f);p.GetComponent<Renderer>().sharedMaterial=material;}prop.gameObject.SetActive(false);}
 void LateUpdate(){if(actor==null||prop==null)return;var clock=actor.Clock;bool loading=actor.Alive&&clock!=null&&clock.Reloading;if(!loading){prop.gameObject.SetActive(false);return;}if(serial!=clock.ReloadSerial){serial=clock.ReloadSerial;started=Time.time;duration=Mathf.Max(.1f,(float)(clock.Deadline-Time.time));}float t=Mathf.Clamp01((Time.time-started)/duration);Quaternion wrist=hand.rotation;Vector3 rest=hand.position;Vector3 axis=actor.muzzle.forward.normalized;
  Vector3 chamber=actor.characterClass==ClassId.Soldier?actor.muzzle.position-axis*.03f+transform.right*.085f:weapon.GetComponent<Renderer>().bounds.center-axis*.12f+transform.right*.04f;
  Vector3 pickup=rest-transform.up*.24f-axis*.08f;Vector3 loadingHand=chamber-axis*(actor.characterClass==ClassId.Soldier?.18f:.055f);Vector3 desired=t<.3f?Vector3.Lerp(rest,pickup,Smooth(t/.3f)):t<.72f?Vector3.Lerp(pickup,loadingHand,Smooth((t-.3f)/.42f)):Vector3.Lerp(loadingHand,rest,Smooth((t-.72f)/.28f));Solve(desired);hand.rotation=wrist;prop.gameObject.SetActive(t>.18f&&t<.78f);prop.position=hand.position+axis*(actor.characterClass==ClassId.Soldier?.10f:.025f);prop.rotation=Quaternion.LookRotation(axis,transform.up);
 }
 static float Smooth(float x)=>x*x*(3-2*x);
 void Solve(Vector3 target){Vector3 shoulder=upper.position,elbow=fore.position,wrist=hand.position;float a=Vector3.Distance(shoulder,elbow),b=Vector3.Distance(elbow,wrist);Vector3 direction=(target-shoulder).normalized;float distance=Mathf.Clamp(Vector3.Distance(target,shoulder),Mathf.Abs(a-b)+.005f,(a+b)*.975f);target=shoulder+direction*distance;Vector3 pole=Vector3.ProjectOnPlane(elbow-shoulder,direction).normalized;if(pole.sqrMagnitude<.1f)pole=-transform.right;float along=(a*a-b*b+distance*distance)/(2*distance);Vector3 desiredElbow=shoulder+direction*along+pole*Mathf.Sqrt(Mathf.Max(0,a*a-along*along));upper.rotation=Quaternion.FromToRotation(elbow-shoulder,desiredElbow-shoulder)*upper.rotation;fore.rotation=Quaternion.FromToRotation(hand.position-fore.position,target-fore.position)*fore.rotation;}
 void OnDestroy(){if(material!=null)Destroy(material);}
}
}
