using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;
namespace FpsStage2 {
public sealed class CPHud:MonoBehaviour {
 public Canvas RootCanvas=>canvas;
 RectTransform safeFrame;CPReticle reticle;float nextPresentation;
 CPMatch match;Canvas canvas;Font font;Text clock,hp,ammo,reserve,notice,result;RawImage playerPortrait;Image hpFill;Image[] pointFill=new Image[3],pointBase=new Image[3];Text[] pointText=new Text[3];GameObject resultPanel;GameObject[] locks=new GameObject[3];readonly List<RawImage> roster=new List<RawImage>();readonly List<CPActor> rosterActors=new List<CPActor>();Texture2D[] gray;Color cream=new Color(.94f,.89f,.73f),dark=new Color(.065f,.075f,.078f,.93f);
 public void Initialize(CPMatch value){match=value;font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");gray=new Texture2D[match.portraits.Length];for(int i=0;i<gray.Length;i++){var src=match.portraits[i];if(src==null)continue;var pixels=src.GetPixels();for(int j=0;j<pixels.Length;j++){float g=pixels[j].grayscale*.65f;pixels[j]=new Color(g,g,g,pixels[j].a);}gray[i]=new Texture2D(src.width,src.height,TextureFormat.RGBA32,false);gray[i].SetPixels(pixels);gray[i].Apply();}
  var go=new GameObject("Powerhouse_HUD",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));go.transform.SetParent(transform,false);canvas=go.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=match.player.playerCamera;canvas.planeDistance=.25f;canvas.sortingOrder=100;var scaler=go.GetComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1600,900);scaler.screenMatchMode=CanvasScaler.ScreenMatchMode.Expand;
  if(CPWebPerformance.Active){canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.worldCamera=null;}
  safeFrame=new GameObject("HUD_SafeFrame",typeof(RectTransform)).GetComponent<RectTransform>();safeFrame.SetParent(canvas.transform,false);safeFrame.anchorMin=Vector2.zero;safeFrame.anchorMax=Vector2.one;safeFrame.offsetMin=safeFrame.offsetMax=Vector2.zero;
  if(FindFirstObjectByType<EventSystem>()==null)new GameObject("Powerhouse_Input",typeof(EventSystem),typeof(InputSystemUIInputModule));
  Panel("Clock",safeFrame,0,416,164,74,dark);clock=Label(safeFrame,"5:00",0,409,160,50,35);Label(safeFrame,"CONTROL POINTS",0,440,160,18,10);
  BuildRoster(CPTeam.RED,-408);BuildRoster(CPTeam.BLU,408);
  for(int i=0;i<3;i++){float x=(i-1)*76;Panel("PointFrame",safeFrame,x,-389,65,65,cream);pointBase[i]=Panel("Point",safeFrame,x,-389,60,60,dark);pointFill[i]=Panel("Capture",pointBase[i].transform,0,0,60,60,Color.white);pointFill[i].rectTransform.pivot=new Vector2(.5f,0);pointFill[i].rectTransform.anchoredPosition=new Vector2(0,-30);pointText[i]=Label(pointBase[i].transform,"",0,0,60,50,22);var symbol=new GameObject("Locked",typeof(RectTransform));symbol.transform.SetParent(pointBase[i].transform,false);Rect(symbol.GetComponent<RectTransform>(),0,0,40,40);locks[i]=symbol;Panel("LockBody",symbol.transform,0,-5,20,17,cream);Panel("ShackleLeft",symbol.transform,-6,7,3,12,cream);Panel("ShackleRight",symbol.transform,6,7,3,12,cream);Panel("ShackleTop",symbol.transform,0,12,13,3,cream);Panel("Keyhole",symbol.transform,0,-4,3,6,dark);Label(safeFrame,i==0?"RED":i==1?"CENTRO":"BLU",x,-435,72,18,12);}
  Panel("PlayerPanel",safeFrame,-650,-377,270,101,new Color(.28f,.09f,.065f,.85f));playerPortrait=Portrait(safeFrame,-683,-343,151,181);Panel("CrossOutlineV",safeFrame,-580,-355,42,98,dark);Panel("CrossOutlineH",safeFrame,-580,-355,94,46,dark);Panel("CrossV",safeFrame,-580,-355,34,90,cream);Panel("CrossH",safeFrame,-580,-355,86,38,cream);hpFill=Panel("HealthTint",safeFrame,-580,-355,70,31,cream);hp=Label(safeFrame,"125",-580,-355,88,48,33);
  Panel("AmmoPlate",safeFrame,671,-382,222,98,new Color(.4f,.12f,.09f,.94f));ammo=Label(safeFrame,"2",650,-376,126,89,76);reserve=Label(safeFrame,"32",740,-395,65,42,33);
  notice=Label(safeFrame,"",0,365,650,44,23);
  var cross=new GameObject("Class_Reticle",typeof(RectTransform),typeof(CPReticle));cross.layer=5;cross.transform.SetParent(canvas.transform,false);reticle=cross.GetComponent<CPReticle>();Rect(reticle.rectTransform,0,0,240,240);
  resultPanel=Panel("RoundResult",safeFrame,0,80,760,290,dark).gameObject;result=Label(resultPanel.transform,"",0,63,710,98,37);Button(resultPanel.transform,"JUGAR OTRA VEZ",0,-80,()=>match.Restart(match.difficulty));resultPanel.SetActive(false);
 }
 int PortraitIndex(CPActor a)=>(a.team==CPTeam.BLU?4:0)+(int)a.characterClass;
 void BuildRoster(CPTeam team,float x){Panel("Roster_"+team,safeFrame,x,416,612,74,dark);Label(safeFrame,team.ToString(),x+(team==CPTeam.RED?-276:276),414,53,40,15);var members=System.Linq.Enumerable.ToArray(System.Linq.Enumerable.OrderBy(System.Linq.Enumerable.Where(match.actors,a=>a.team==team),a=>(int)a.characterClass));float stride=532f/Mathf.Max(1,members.Length);for(int n=0;n<members.Length;n++){var a=members[n];float px=x+(team==CPTeam.RED?28:-28)-266+(n+.5f)*stride,w=Mathf.Min(62,stride-5);var p=Portrait(safeFrame,px,418,w,64);var texture=match.portraits[PortraitIndex(a)];float uvWidth=texture!=null?.38f*texture.height/texture.width*w/64:.44f;p.uvRect=new Rect(.5f-uvWidth/2,.57f,uvWidth,.38f);roster.Add(p);rosterActors.Add(a);Panel("TeamHealthLine",safeFrame,px,382,stride-5,4,CPMatch.TeamColor(team));}}
 Image Panel(string name,Transform parent,float x,float y,float w,float h,Color color){var go=new GameObject(name,typeof(RectTransform),typeof(Image));go.layer=5;go.transform.SetParent(parent,false);var image=go.GetComponent<Image>();image.color=color;image.raycastTarget=false;Rect(image.rectTransform,x,y,w,h);return image;}
 void Rect(RectTransform r,float x,float y,float w,float h){Vector2 anchor=new Vector2(.5f,.5f);if(r.parent==safeFrame){if(y>=350){anchor=new Vector2(.5f,1);y-=468;}else if(y<-200){anchor=new Vector2(x<-400?0:x>400?1:.5f,0);y+=468;if(x<-400)x+=818;else if(x>400)x-=818;}}r.anchorMin=r.anchorMax=anchor;r.anchoredPosition=new Vector2(x,y);r.sizeDelta=new Vector2(w,h);}
 Text Label(Transform parent,string value,float x,float y,float w,float h,int size){var go=new GameObject("Text_"+value,typeof(RectTransform),typeof(Text));go.layer=5;go.transform.SetParent(parent,false);var t=go.GetComponent<Text>();t.font=font;t.text=value;t.fontSize=size;t.color=cream;t.alignment=TextAnchor.MiddleCenter;t.raycastTarget=false;Rect(t.rectTransform,x,y,w,h);var shadow=go.AddComponent<Shadow>();shadow.effectColor=new Color(0,0,0,.5f);shadow.effectDistance=new Vector2(1,-1);return t;}
 RawImage Portrait(Transform parent,float x,float y,float w,float h){var go=new GameObject("Portrait",typeof(RectTransform),typeof(RawImage));go.layer=5;go.transform.SetParent(parent,false);var r=go.GetComponent<RawImage>();r.raycastTarget=false;Rect(r.rectTransform,x,y,w,h);return r;}
 void Button(Transform parent,string text,float x,float y,UnityEngine.Events.UnityAction action){var panel=Panel(text,parent,x,y,400,53,new Color(.29f,.31f,.29f));panel.raycastTarget=true;var button=panel.gameObject.AddComponent<Button>();button.targetGraphic=panel;button.onClick.AddListener(action);Label(panel.transform,text,0,0,380,51,23);}
 void LateUpdate(){if(match==null||match.PlayerActor==null)return;ApplySafeArea();reticle.enabled=!match.InputBlocked;reticle.Present(match.player.currentClass,match.player.playerCamera,match.player.Clock,Time.unscaledDeltaTime);if(Time.unscaledTime<nextPresentation)return;nextPresentation=Time.unscaledTime+.06f;var rules=match.rules;int seconds=Mathf.CeilToInt(rules.Remaining);clock.text=rules.Overtime?"OVERTIME":$"{seconds/60}:{seconds%60:00}";clock.fontSize=rules.Overtime?22:35;clock.color=rules.Overtime?new Color(1,.54f,.18f):cream;
  for(int i=0;i<roster.Count;i++){var a=rosterActors[i];int p=PortraitIndex(a);roster[i].texture=a.Alive?match.portraits[p]:gray[p];}
  var player=match.PlayerActor;playerPortrait.uvRect=new Rect(.12f,0,.8f,1);playerPortrait.texture=player.Alive?match.portraits[PortraitIndex(player)]:gray[PortraitIndex(player)];hp.text=Mathf.CeilToInt(player.health).ToString();hpFill.color=player.HealthFraction<.3f?new Color(.85f,.26f,.18f):cream;hp.color=dark;ammo.text=player.Clock.Ammo.ToString();reserve.text=player.characterClass==ClassId.Scout||player.characterClass==ClassId.Soldier?player.Clock.Reserve.ToString():"";
  string message="";for(int i=0;i<3;i++){var p=rules.Points[i];pointBase[i].color=CPMatch.TeamColor(p.Owner);pointFill[i].color=CPMatch.TeamColor(p.Capturing);pointFill[i].gameObject.SetActive(p.Progress>.001f);pointFill[i].rectTransform.sizeDelta=new Vector2(60,60*p.Progress);locks[i].SetActive(p.Locked);pointText[i].text=p.Locked?"":p.Contested?"!":((char)('A'+i)).ToString();if(match.zones[i].Contains(player.transform.position))message=p.Locked?"PUNTO BLOQUEADO":p.Contested?"PUNTO DISPUTADO":p.Owner==player.team?"DEFENDIENDO":$"CAPTURANDO {Mathf.FloorToInt(p.Progress*100)}%";}
  if(!player.Alive)message=$"REAPARICIÓN EN {Mathf.Max(0,Mathf.CeilToInt(player.respawnAt-Time.time))} s";notice.text=message;resultPanel.SetActive(rules.Finished&&!match.MenuOpen);if(rules.Finished)result.text=(rules.Winner==CPTeam.Neutral?"EMPATE":"VICTORIA DE "+rules.Winner)+"\n<size=19>"+rules.EndReason+"</size>";
 }
 public void ApplySafeArea(){var cam=match.player.playerCamera;var viewport=cam.pixelRect;if(viewport.width<=0||viewport.height<=0)return;var area=cam.targetTexture!=null?viewport:Screen.safeArea;safeFrame.anchorMin=new Vector2(Mathf.Clamp01((area.xMin-viewport.xMin)/viewport.width),Mathf.Clamp01((area.yMin-viewport.yMin)/viewport.height));safeFrame.anchorMax=new Vector2(Mathf.Clamp01((area.xMax-viewport.xMin)/viewport.width),Mathf.Clamp01((area.yMax-viewport.yMin)/viewport.height));safeFrame.offsetMin=safeFrame.offsetMax=Vector2.zero;}
 void OnDestroy(){if(gray!=null)foreach(var t in gray)if(t!=null)Destroy(t);}
}
}
