using UnityEngine;
namespace FpsStage2 {
// Six reusable bursts; no Instantiate, new materials, or meshes when rockets impact.
public sealed class CPRocketBurst:MonoBehaviour {
 class Burst {public Transform root;public ParticleSystem fire,smoke,sparks;public Light flash;public LineRenderer wave;public float age=9;}
 readonly Burst[] pool=new Burst[6];int next;Material flameMat,smokeMat,sparkMat;Camera camera;
 public void Initialize(Camera cam,Texture flame,Texture soft){camera=cam;flameMat=MaterialFor(flame);smokeMat=MaterialFor(soft);sparkMat=MaterialFor(soft);
  for(int i=0;i<pool.Length;i++){var go=new GameObject("Rocket_Burst_"+i);go.transform.SetParent(transform,false);var b=new Burst{root=go.transform};b.fire=System(go.transform,"Fireball",flameMat,96,.43f);b.smoke=System(go.transform,"Smoke",smokeMat,120,1.9f);b.sparks=System(go.transform,"Sparks",sparkMat,80,.65f);var main=b.sparks.main;main.gravityModifier=.65f;
   var size=b.fire.sizeOverLifetime;size.enabled=true;size.size=new ParticleSystem.MinMaxCurve(1,new AnimationCurve(new Keyframe(0,.2f),new Keyframe(.22f,1),new Keyframe(1,1.8f)));var smokeSize=b.smoke.sizeOverLifetime;smokeSize.enabled=true;smokeSize.size=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,.35f,1,1.5f));
   GradientColor(b.fire,new Color(2,1.05f,.24f),new Color(.75f,.09f,.01f));GradientColor(b.smoke,new Color(.25f,.22f,.19f),new Color(.13f,.14f,.15f));GradientColor(b.sparks,new Color(3,1.5f,.18f),new Color(.65f,.13f,.005f));var smokeFade=b.smoke.colorOverLifetime;var sg=smokeFade.color.gradient;sg.SetKeys(sg.colorKeys,new[]{new GradientAlphaKey(0,0),new GradientAlphaKey(.12f,.15f),new GradientAlphaKey(.48f,.38f),new GradientAlphaKey(.25f,.7f),new GradientAlphaKey(0,1)});smokeFade.color=sg;
   b.flash=go.AddComponent<Light>();b.flash.type=LightType.Point;b.flash.range=8;b.flash.color=new Color(1,.43f,.1f);b.flash.shadows=LightShadows.None;b.flash.enabled=false;
   var ring=new GameObject("Pressure_Wave");ring.transform.SetParent(go.transform,false);b.wave=ring.AddComponent<LineRenderer>();b.wave.sharedMaterial=sparkMat;b.wave.useWorldSpace=false;b.wave.loop=true;b.wave.positionCount=48;b.wave.widthMultiplier=.05f;b.wave.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;for(int k=0;k<48;k++){float a=k*Mathf.PI*2/48;b.wave.SetPosition(k,new Vector3(Mathf.Cos(a),Mathf.Sin(a),0));}b.wave.enabled=false;pool[i]=b;
  }
 }
 static Material MaterialFor(Texture t){var m=new Material(Shader.Find("Universal Render Pipeline/Particles/Unlit"));m.SetFloat("_Surface",1);m.SetFloat("_Blend",0);m.SetFloat("_SrcBlend",(float)UnityEngine.Rendering.BlendMode.SrcAlpha);m.SetFloat("_DstBlend",(float)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);m.SetFloat("_ZWrite",0);m.SetFloat("_Cull",0);m.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");m.renderQueue=3000;m.SetTexture("_BaseMap",t);m.SetColor("_BaseColor",Color.white);return m;}
 static ParticleSystem System(Transform parent,string name,Material material,int count,float life){var go=new GameObject(name);go.transform.SetParent(parent,false);var ps=go.AddComponent<ParticleSystem>();ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);var main=ps.main;main.playOnAwake=false;main.loop=false;main.simulationSpace=ParticleSystemSimulationSpace.World;main.maxParticles=count;main.startLifetime=life;main.startSpeed=0;var emit=ps.emission;emit.enabled=false;var shape=ps.shape;shape.enabled=false;var renderer=ps.GetComponent<ParticleSystemRenderer>();renderer.sharedMaterial=material;renderer.sortMode=ParticleSystemSortMode.Distance;renderer.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;return ps;}
 static void GradientColor(ParticleSystem ps,Color a,Color b){var module=ps.colorOverLifetime;module.enabled=true;var g=new Gradient();g.SetKeys(new[]{new GradientColorKey(a,0),new GradientColorKey(b,1)},new[]{new GradientAlphaKey(0,0),new GradientAlphaKey(.85f,.07f),new GradientAlphaKey(.5f,.45f),new GradientAlphaKey(0,1)});module.color=g;}
 public void Emit(Vector3 p){var b=pool[next++%pool.Length];b.age=0;b.root.position=p;b.flash.enabled=CPQualityEffects.Current==CPGraphicsQuality.Ultra;b.flash.intensity=5;b.wave.enabled=CPQualityEffects.Current==CPGraphicsQuality.Ultra;b.wave.transform.rotation=camera.transform.rotation;b.wave.transform.localScale=Vector3.one*.15f;b.wave.startColor=b.wave.endColor=new Color(1,.68f,.25f,.27f);
  Spawn(b.fire,p,26,1.1f,1.85f,2.8f,.32f,.6f);Spawn(b.smoke,p,16,.8f,1.3f,1.8f,1.1f,1.9f);Spawn(b.sparks,p,32,.045f,.09f,7,.2f,.75f);var core=new ParticleSystem.EmitParams{position=p,velocity=Vector3.zero,startSize=1.9f,startLifetime=.19f,startColor=new Color(1,1,.82f)};b.sparks.Emit(core,1);CPMatch.Instance?.audioSystem?.Play(CPSound.Explosion,p);
 }
 static void Spawn(ParticleSystem ps,Vector3 p,int count,float minSize,float maxSize,float speed,float minLife,float maxLife){ps.Clear();ps.Play();bool smoke=ps.name=="Smoke";count=CPQualityEffects.Count(count,smoke);float lifetime=CPQualityEffects.Current==CPGraphicsQuality.Ultra?1:smoke?.55f:.8f;for(int i=0;i<count;i++){Vector3 dir=Random.onUnitSphere;var emit=new ParticleSystem.EmitParams{position=p+dir*Random.Range(0,.20f),velocity=dir*Random.Range(.2f,speed)+Vector3.up*.8f,startSize=Random.Range(minSize,maxSize),startLifetime=Random.Range(minLife,maxLife)*lifetime,rotation=Random.Range(0,360)};ps.Emit(emit,1);}}
 void Update(){foreach(var b in pool){if(b==null||b.age>2)continue;b.age+=Time.deltaTime;b.flash.intensity=5*Mathf.Clamp01(1-b.age/.14f);bool ultra=CPQualityEffects.Current==CPGraphicsQuality.Ultra;b.flash.enabled=ultra&&b.age<.14f;b.wave.enabled=ultra&&b.age<.25f;if(b.wave.enabled){b.wave.transform.localScale=Vector3.one*Mathf.Lerp(.15f,3.3f,b.age/.25f);var c=new Color(1,.68f,.25f,.27f*(1-b.age/.25f));b.wave.startColor=b.wave.endColor=c;}}}
 void OnDestroy(){if(flameMat!=null)Destroy(flameMat);if(smokeMat!=null)Destroy(smokeMat);if(sparkMat!=null)Destroy(sparkMat);}
}
}
