using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;
using UnityEditor;
using UnityEditor.SceneManagement;
namespace FpsStage2 {
public static class CPSetup {
 const string Root="Assets/ControlPoints";
 [MenuItem("Powerhouse/Configure Control Point Match")]
 public static string Configure(){
  if(Application.isPlaying)throw new Exception("Stop Play mode before configuring the match.");
  NavMesh.RemoveAllNavMeshData();var nav=AssetDatabase.LoadAssetAtPath<NavMeshData>(Root+"/Navigation/PowerhouseNavigation.asset");var instance=NavMesh.AddNavMeshData(nav);
  var player=UnityEngine.Object.FindFirstObjectByType<FpsStage2Player>();var root=GameObject.Find("ControlPointMatch")??new GameObject("ControlPointMatch");var match=Get<CPMatch>(root);Get<CPCombat>(root);Get<CPHud>(root);match.player=player;match.navigation=nav;
  match.portraits=new Texture2D[8];for(int t=0;t<2;t++)for(int c=0;c<4;c++){string path=Root+"/Portraits/"+(t==0?"RED":"BLU")+"_"+(ClassId)c+".png";var importer=(TextureImporter)AssetImporter.GetAtPath(path);if(importer!=null){importer.isReadable=true;importer.alphaIsTransparency=true;importer.mipmapEnabled=false;importer.textureCompression=TextureImporterCompression.Uncompressed;importer.SaveAndReimport();}match.portraits[t*4+c]=AssetDatabase.LoadAssetAtPath<Texture2D>(path);}
  var pa=Get<CPActor>(player.gameObject);pa.team=CPTeam.RED;pa.isPlayer=true;pa.characterClass=player.currentClass;player.gameObject.layer=8;
  var bots=UnityEngine.Object.FindObjectsByType<StaticBotIdentity>(FindObjectsSortMode.None);foreach(var b in bots){var a=Get<CPActor>(b.gameObject);a.team=b.team=="RED"?CPTeam.RED:CPTeam.BLU;a.characterClass=b.characterClass;b.gameObject.layer=8;var agent=Get<NavMeshAgent>(b.gameObject);agent.radius=.36f;agent.height=1.85f;agent.acceleration=22;agent.angularSpeed=360;agent.stoppingDistance=.3f;agent.speed=player.speeds[(int)b.characterClass];agent.obstacleAvoidanceType=ObstacleAvoidanceType.HighQualityObstacleAvoidance;var capsule=b.GetComponent<CapsuleCollider>();capsule.radius=.37f;capsule.height=1.85f;capsule.center=new Vector3(0,.925f,0);
   var brain=Get<CPBrain>(b.gameObject);Get<CPBotReload>(b.gameObject);brain.animations=b.GetComponentInChildren<Animation>();brain.spine=b.GetComponentsInChildren<Transform>().First(x=>x.name=="Spine");CreateAnimations(brain,b.characterClass);
   var weapon=b.GetComponentsInChildren<MeshRenderer>().First(x=>x.name.EndsWith("_Weapon"));var m=weapon.transform.Find("CP_Muzzle");if(m==null){m=new GameObject("CP_Muzzle").transform;m.SetParent(weapon.transform,false);}var verts=weapon.GetComponent<MeshFilter>().sharedMesh.vertices.Select(v=>weapon.transform.TransformPoint(v)).ToArray();float max=verts.Max(v=>Vector3.Dot(v-b.transform.position,b.transform.forward));var tip=verts.Where(v=>Vector3.Dot(v-b.transform.position,b.transform.forward)>max-.025f).ToArray();Vector3 center=Vector3.zero;foreach(var v in tip)center+=v;center/=tip.Length;m.position=center+b.transform.forward*.025f;m.rotation=Quaternion.LookRotation(b.transform.forward);a.muzzle=m;
   if(b.characterClass==ClassId.Heavy){var motor=weapon.GetComponent<CPBotMotor>();if(motor!=null){float front=motor.originalMesh.vertices.Max(v=>Vector3.Dot(v-motor.spindle.localPosition,motor.axis));m.localPosition=motor.spindle.localPosition+motor.axis*(front+.0002f);m.localRotation=Quaternion.LookRotation(motor.axis);}else HeavySpindle(b,weapon,a);}
   NavMeshHit h;if(NavMesh.SamplePosition(b.transform.position,out h,3,-1))b.transform.position=h.position;EditorUtility.SetDirty(b.gameObject);
  }
  match.zones=new[]{Zone(root.transform,"Punto_RED_Base",new Vector3(93.4f,5.07f,-2.34f),CPTeam.RED),Zone(root.transform,"Punto_Centro",new Vector3(0,1.29f,-12.2f),CPTeam.Neutral),Zone(root.transform,"Punto_BLU_Base",new Vector3(-93.4f,5.07f,-2.34f),CPTeam.BLU)};
  var centerGlow=GameObject.Find("Powerhouse").GetComponentsInChildren<Renderer>().FirstOrDefault(r=>r.name=="PH_05_ControlPoint_PH_Capture_Light_0_-1_0_Visual");if(centerGlow!=null)match.zones[1].glowRenderers=match.zones[1].glowRenderers.Concat(new[]{centerGlow}).ToArray();
  var stations=new List<Vector3>();foreach(float sign in new[]{-1f,1f})foreach(var p in new[]{new Vector3(116,4.71f,10),new Vector3(63,4.71f,4),new Vector3(21,2.91f,-7)}){NavMeshHit h;var pos=new Vector3(p.x*sign,p.y,p.z);if(NavMesh.SamplePosition(pos,out h,5,-1)){stations.Add(h.position);Station(root.transform,h.position,stations.Count);}}match.healthStations=stations.ToArray();
  var nodes=new List<Vector3>();var mesh=NavMesh.CalculateTriangulation();foreach(var v in mesh.vertices){if(v.y<0||v.y>14)continue;if(nodes.All(n=>(n-v).sqrMagnitude>25))nodes.Add(v);}match.strategicNodes=nodes.ToArray();
  EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene(EditorSceneManager.GetActiveScene().path,true)};EditorUtility.SetDirty(match);AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene());instance.Remove();return $"Configured {bots.Length} bots, 3 zones, {nodes.Count} tactical nodes and {stations.Count} supply stations.";
 }
 static T Get<T>(GameObject go)where T:Component{var c=go.GetComponent<T>();return c!=null?c:go.AddComponent<T>();}
 static Material Mat(string name,Color color){string path=Root+"/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(m==null){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,path);}m.SetColor("_BaseColor",color);m.SetColor("_EmissionColor",color*1.6f);m.EnableKeyword("_EMISSION");return m;}
 static CPZone Zone(Transform parent,string name,Vector3 pos,CPTeam team){var t=parent.Find(name);if(t==null){t=new GameObject(name).transform;t.SetParent(parent,false);}t.position=pos;var renderers=new List<Renderer>();for(int i=0;i<32;i++){var ring=t.Find("Ring_"+i);if(ring==null){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.name="Ring_"+i;ring=go.transform;ring.SetParent(t,false);UnityEngine.Object.DestroyImmediate(go.GetComponent<Collider>());}float angle=i*360f/32;ring.localPosition=new Vector3(Mathf.Sin(angle*Mathf.Deg2Rad)*2.85f,.035f,Mathf.Cos(angle*Mathf.Deg2Rad)*2.85f);ring.localRotation=Quaternion.Euler(0,angle,0);ring.localScale=new Vector3(.52f,.06f,.13f);var r=ring.GetComponent<Renderer>();r.sharedMaterial=Mat("ControlPointGlow",CPMatch.TeamColor(team));renderers.Add(r);}return new CPZone{label=name,position=pos,radius=3.2f,height=2.8f,visual=t,glowRenderers=renderers.ToArray()};}
 static void Station(Transform parent,Vector3 point,int index){if(parent.Find("Supply_"+index)!=null)return;var root=new GameObject("Supply_"+index).transform;root.SetParent(parent,false);root.position=point;var box=GameObject.CreatePrimitive(PrimitiveType.Cube);box.name="MedicalAmmoCrate";box.transform.SetParent(root,false);box.transform.localPosition=Vector3.up*.24f;box.transform.localScale=new Vector3(.7f,.45f,.45f);UnityEngine.Object.DestroyImmediate(box.GetComponent<Collider>());box.GetComponent<Renderer>().sharedMaterial=Mat("SupplyGreen",new Color(.11f,.25f,.19f));foreach(var s in new[]{new Vector3(.12f,.3f,.03f),new Vector3(.3f,.12f,.03f)}){var cross=GameObject.CreatePrimitive(PrimitiveType.Cube);cross.name="HealthCross";cross.transform.SetParent(root,false);cross.transform.localPosition=new Vector3(0,.24f,-.24f);cross.transform.localScale=s;UnityEngine.Object.DestroyImmediate(cross.GetComponent<Collider>());cross.GetComponent<Renderer>().sharedMaterial=Mat("SupplyCross",new Color(.9f,.85f,.65f));}}
 static void CreateAnimations(CPBrain brain,ClassId id){var a=brain.animations;var idle=a["Idle"].clip;idle.SampleAnimation(a.gameObject,0);foreach(string kind in new[]{"Jump"}){string path=Root+"/Animations/"+id+"_"+kind+".anim";var clip=AssetDatabase.LoadAssetAtPath<AnimationClip>(path);if(clip==null){clip=new AnimationClip();AssetDatabase.CreateAsset(clip,path);}clip.ClearCurves();clip.legacy=true;clip.wrapMode=WrapMode.Loop;clip.frameRate=30;float length=kind=="Run"?.7f:.65f;var bones=a.GetComponentsInChildren<Transform>().Where(t=>t!=a.transform).ToArray();var rotation=bones.Select(t=>t.localRotation).ToArray();var position=bones.Select(t=>t.localPosition).ToArray();var curves=new Dictionary<string,AnimationCurve[]>();foreach(var t in bones)curves[AnimationUtility.CalculateTransformPath(t,a.transform)]=Enumerable.Range(0,7).Select(i=>new AnimationCurve()).ToArray();
   for(int f=0;f<=30;f++){float time=length*f/30,phase=f/30f*Mathf.PI*2;for(int k=0;k<bones.Length;k++){var bone=bones[k];var rot=rotation[k];var pos=position[k];float sign=bone.name.StartsWith("Left")?1:-1;float swing=Mathf.Sin(phase)*sign;
    if(kind=="Run"){if(bone.name.EndsWith("UpLeg"))rot*=Quaternion.Euler(swing*24,0,0);else if(bone.name=="LeftLeg"||bone.name=="RightLeg")rot*=Quaternion.Euler(Mathf.Max(0,-swing)*26-9,0,0);else if(bone.name.EndsWith("Foot"))rot*=Quaternion.Euler(-swing*11,0,0);else if(bone.name=="Hips")pos+=bone.parent.InverseTransformVector(Vector3.up*(.025f+.025f*Mathf.Cos(phase*2)));else if(bone.name=="Spine")rot*=Quaternion.Euler(1.4f*Mathf.Cos(phase*2),Mathf.Sin(phase)*1.5f,0);}
    else{float tuck=Mathf.Sin(f/30f*Mathf.PI);if(bone.name.EndsWith("UpLeg"))rot*=Quaternion.Euler(-18*tuck,0,0);else if(bone.name=="LeftLeg"||bone.name=="RightLeg")rot*=Quaternion.Euler(28*tuck,0,0);else if(bone.name.EndsWith("Foot"))rot*=Quaternion.Euler(-10*tuck,0,0);}
    var c=curves[AnimationUtility.CalculateTransformPath(bone,a.transform)];c[0].AddKey(time,rot.x);c[1].AddKey(time,rot.y);c[2].AddKey(time,rot.z);c[3].AddKey(time,rot.w);c[4].AddKey(time,pos.x);c[5].AddKey(time,pos.y);c[6].AddKey(time,pos.z);
   }}foreach(var pair in curves){string[] properties={"localRotation.x","localRotation.y","localRotation.z","localRotation.w","localPosition.x","localPosition.y","localPosition.z"};for(int i=0;i<7;i++){for(int key=0;key<pair.Value[i].length;key++)pair.Value[i].SmoothTangents(key,0);clip.SetCurve(pair.Key,typeof(Transform),properties[i],pair.Value[i]);}}clip.EnsureQuaternionContinuity();EditorUtility.SetDirty(clip);a.AddClip(clip,kind);a[kind].wrapMode=WrapMode.Loop;}
  string firePath=Root+"/Animations/"+id+"_Fire.anim";var fire=AssetDatabase.LoadAssetAtPath<AnimationClip>(firePath);if(fire==null){fire=new AnimationClip();AssetDatabase.CreateAsset(fire,firePath);}fire.ClearCurves();fire.legacy=true;fire.wrapMode=WrapMode.Once;float duration=id==ClassId.Soldier?.6f:id==ClassId.Scout?.3125f:.1f;Quaternion kick=Quaternion.Euler(id==ClassId.Scout?-4:id==ClassId.Soldier?-3:-1.2f,0,0);var pathSpine=AnimationUtility.CalculateTransformPath(brain.spine,a.transform);string[] channel={"x","y","z","w"};for(int c=0;c<4;c++){var curve=new AnimationCurve(new Keyframe(0,c==3?1:0),new Keyframe(duration*.14f,kick[c]),new Keyframe(duration,c==3?1:0));for(int k=0;k<3;k++)curve.SmoothTangents(k,0);fire.SetCurve(pathSpine,typeof(Transform),"localRotation."+channel[c],curve);}fire.EnsureQuaternionContinuity();EditorUtility.SetDirty(fire);a.AddClip(fire,"Fire");a["Fire"].layer=1;a["Fire"].blendMode=AnimationBlendMode.Additive;a["Fire"].wrapMode=WrapMode.Once;
  CPGaitBuilder.Build(brain,id);idle.SampleAnimation(a.gameObject,0);a.playAutomatically=true;EditorUtility.SetDirty(a);
 }
 static void HeavySpindle(StaticBotIdentity bot,MeshRenderer weapon,CPActor actor){if(weapon.GetComponent<CPBotMotor>()!=null)return;var filter=weapon.GetComponent<MeshFilter>();var original=filter.sharedMesh;var local=original.vertices;var body=local.Select(v=>bot.transform.InverseTransformPoint(weapon.transform.TransformPoint(v))).ToArray();float front=body.Max(p=>p.z);Func<float,Vector3> center=depth=>{var band=body.Where(p=>Mathf.Abs(p.z-(front-depth))<.025f).ToArray();var bounds=new Bounds(band[0],Vector3.zero);foreach(var p in band)bounds.Encapsulate(p);return bounds.center;};Vector3 forward=(center(.2f)-center(.4f)).normalized,pivot=center(.4f);var turn=new List<int>();var fixedPart=new List<int>();var tri=original.triangles;for(int i=0;i<tri.Length;i+=3){Vector3 p=(body[tri[i]]+body[tri[i+1]]+body[tri[i+2]])/3;var list=p.z>front-.50f&&Vector3.ProjectOnPlane(p-pivot,forward).magnitude<.17f?turn:fixedPart;list.Add(tri[i]);list.Add(tri[i+1]);list.Add(tri[i+2]);}if(turn.Count<100)throw new Exception("Heavy spindle segmentation failed");
  var stationary=UnityEngine.Object.Instantiate(original);stationary.name="Heavy_FixedHousing";stationary.triangles=fixedPart.ToArray();var rotating=UnityEngine.Object.Instantiate(original);rotating.name="Heavy_RotatingBarrels";rotating.triangles=turn.ToArray();string path=Root+"/Animations/Heavy_FixedHousing.asset";var existing=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(existing==null)AssetDatabase.CreateAsset(stationary,path);else{EditorUtility.CopySerialized(stationary,existing);UnityEngine.Object.DestroyImmediate(stationary);stationary=existing;}path=Root+"/Animations/Heavy_RotatingBarrels.asset";existing=AssetDatabase.LoadAssetAtPath<Mesh>(path);if(existing==null)AssetDatabase.CreateAsset(rotating,path);else{EditorUtility.CopySerialized(rotating,existing);UnityEngine.Object.DestroyImmediate(rotating);rotating=existing;}filter.sharedMesh=stationary;
  var spindle=new GameObject("CP_FixedAxisSpindle").transform;spindle.SetParent(weapon.transform,false);spindle.position=bot.transform.TransformPoint(pivot);var shell=new GameObject("RotatingBarrels",typeof(MeshFilter),typeof(MeshRenderer));shell.transform.SetParent(spindle,false);shell.transform.localPosition=-spindle.localPosition;shell.GetComponent<MeshFilter>().sharedMesh=rotating;shell.GetComponent<MeshRenderer>().sharedMaterials=weapon.sharedMaterials;var motor=weapon.gameObject.AddComponent<CPBotMotor>();motor.spindle=spindle;motor.axis=weapon.transform.InverseTransformDirection(bot.transform.TransformDirection(forward)).normalized;motor.originalMesh=original;actor.muzzle.position=bot.transform.TransformPoint(pivot+forward*((front-pivot.z)/forward.z+.02f));actor.muzzle.rotation=Quaternion.LookRotation(bot.transform.TransformDirection(forward));
 }
}
}
