using System;
using UnityEngine;
using UnityEngine.AI;
using System.Linq;
namespace FpsStage2 {
public static class CPTests {
 static int count;static void Check(bool ok,string name){if(!ok)throw new Exception("FAILED: "+name);count++;}static bool Near(float a,float b)=>Math.Abs(a-b)<.003f;
 static int[] N(int a=0,int b=0,int c=0)=>new[]{a,b,c};
 public static string Rules(){count=0;var r=new ControlPointRules();Check(r.Points[0].Locked&&r.Points[2].Locked&&!r.Points[1].Locked,"initial locks");Check(r.Points[0].Owner==CPTeam.RED&&r.Points[1].Owner==CPTeam.Neutral&&r.Points[2].Owner==CPTeam.BLU,"initial owners");Check(Near(r.Remaining,300),"five minutes");r.Tick(10,N(0,0,1),N(1));Check(!r.Finished&&r.Points[0].Owner==CPTeam.RED&&r.Points[2].Owner==CPTeam.BLU,"locked bases immune");
  r.Reset();r.Tick(r.CenterSeconds/2,N(0,1),N());Check(Near(r.Points[1].Progress,.5f),"solo halfway");r.Tick(2,N(0,1),N(0,1));Check(Near(r.Points[1].Progress,.5f),"contested frozen");r.Tick(r.CenterSeconds/2,N(0,1),N());Check(r.Points[1].Owner==CPTeam.RED&&!r.Points[2].Locked&&r.Points[0].Locked,"RED center unlocks BLU");Check(Near(r.Remaining,334)&&r.CenterCaptures==1,"center bonus once");r.Tick(r.CenterSeconds,N(),N(0,1));Check(r.Points[1].Owner==CPTeam.BLU&&!r.Points[0].Locked&&r.Points[2].Locked,"BLU recapture flips locks");Check(r.CenterCaptures==2&&Near(r.Remaining,370),"recapture bonus");Check(Near(r.RespawnDelay(CPTeam.RED),9)&&Near(r.RespawnDelay(CPTeam.BLU),5),"defender respawn penalty");r.Tick(r.BaseSeconds,N(),N(1));Check(r.Finished&&r.Winner==CPTeam.BLU,"BLU base victory");
  r.Reset();r.Tick(r.CenterSeconds,N(0,1),N());r.Tick(r.BaseSeconds,N(0,0,1),N());Check(r.Finished&&r.Winner==CPTeam.RED,"RED base victory");Check(Near(r.CaptureSeconds(1,2),18f)&&Near(r.CaptureSeconds(1,3),13.5f)&&Near(r.CaptureSeconds(0,2),24),"multiplicative capture acceleration");
  r.Reset();r.Tick(18f,N(0,2),N());Check(r.Points[1].Owner==CPTeam.RED,"two-player exact capture");r.Reset();r.Remaining=1;r.Tick(1,N(0,1),N(0,1));Check(r.Overtime&&!r.Finished,"contested overtime");r.Tick(.01f,N(),N());Check(r.Finished&&r.Winner==CPTeam.Neutral,"empty overtime draw immediately");
  r.Reset();r.Remaining=1;r.Tick(1,N(0,1),N());Check(r.Overtime,"attacker at expiration");r.Tick(r.CenterSeconds-1,N(0,1),N());Check(r.Finished&&r.Winner==CPTeam.RED,"center overtime capture wins");r.Reset();r.Tick(300,N(),N());Check(r.Finished&&r.Winner==CPTeam.Neutral,"neutral timeout draw");
  r.Reset();r.Tick(r.CenterSeconds,N(0,1),N());r.Remaining=.5f;r.Tick(.5f,N(0,1),N());Check(r.Finished&&r.Winner==CPTeam.RED,"owner alone is not overtime attacker");r.Reset();r.Tick(r.CenterSeconds,N(0,1),N());r.Remaining=.5f;r.Tick(.5f,N(),N(0,1));Check(r.Overtime,"recapture attacker triggers OT");r.Tick(.1f,N(),N());Check(r.Finished&&r.Winner==CPTeam.RED,"defender expels attackers");
  var a=new ControlPointRules();var b=new ControlPointRules();a.Tick(48,N(0,1),N());for(int i=0;i<480;i++)b.Tick(.1f,N(0,1),N());Check(a.Points[1].Owner==b.Points[1].Owner&&Math.Abs(a.Remaining-b.Remaining)<.03f,"frame subdivision consistency");r.Reset();r.Tick(r.CenterSeconds/2,N(0,1),N());r.Tick(1,N(),N());Check(Near(r.Points[1].Progress,.25f),"abandoned progress decays");
  var w=new WeaponClock(ClassId.Soldier);Check(w.Ammo==4,"Soldier 4 loaded");Check(w.Step(0,true,false,false)==1,"Soldier fires");w.Step(.8,false,false,false);Check(w.Reloading,"Soldier automatic reload");Check(w.Step(.8,true,false,false)==1&&!w.Reloading,"fire interrupts reload after 0.8");Check(w.Step(1.59,true,false,false)==0,"cannot shoot before interval");w.Step(1.6,false,false,false);w.Step(2.52,false,false,false);Check(w.Ammo==3,"first rocket reload .92");w.Step(3.32,false,false,false);Check(w.Ammo==4&&!w.Reloading,"next rocket reload .8");var h=new WeaponClock(ClassId.Heavy);Check(h.Step(0,true,false,false)==0&&h.Spinning,"Heavy left spins");Check(h.Step(1.10,true,false,false)==1,"Heavy left warmup 1.10");Check(h.Step(1.22,true,false,false)==1&&h.Spinning,"Heavy retains motor with left only");
  return count+" rule and weapon assertions passed";
 }
 public static string Navigation(){var m=UnityEngine.Object.FindFirstObjectByType<CPMatch>();var nav=NavMesh.AddNavMeshData(m.navigation);int ok=0;try{foreach(var b in UnityEngine.Object.FindObjectsByType<StaticBotIdentity>(FindObjectsSortMode.None))foreach(var z in m.zones){var path=new NavMeshPath();Check(NavMesh.CalculatePath(b.transform.position,z.position,-1,path)&&path.status==NavMeshPathStatus.PathComplete,b.name+" -> "+z.label);ok++;}}finally{nav.Remove();}return ok+" complete bot-to-point routes";}
}
}
